abstract: Create PAR distributions from CPAN
author: Steffen Mueller (smueller@cpan.org)
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: PAR-Dist-FromCPAN
no_index: 
  directory: 
    - inc
    - t
version: 0.01
