--- 
abstract: Create PAR distributions from CPAN
author: Steffen Mueller (smueller@cpan.org)
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: PAR-Dist-FromCPAN
no_index: 
  directory: 
    - inc
    - t
requires: 
  CPAN: 1.84
  Cwd: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  Module::CoreList: 0
  PAR::Dist: 0.22
  perl: 5.6.0
version: 0.05
